#!/data/data/com.termux/files/usr/bin/bash

## ANSI Renk Kodları
RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"  CYAN="$(printf '\033[36m')"  WHITE="$(printf '\033[37m')" BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"  GREENBG="$(printf '\033[42m')"  ORANGEBG="$(printf '\033[43m')"  BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"  CYANBG="$(printf '\033[46m')"  WHITEBG="$(printf '\033[47m')" BLACKBG="$(printf '\033[40m')"

## Renkleri Sıfırla
reset_color() {
	printf '\033[37m'
}




#Kur
install_rs() {
	clear
	banner
	echo " "
	echo "[*] Dosya Sistemi İndiriliyor..."
	wget -P $HOME/filesystem.RSU https://turkishcydia.github.io/ROSA/filesystem/filesystem.RSV
	sleep 2
	echo " "
	echo "[*] Dosya Sistemi Ayıklanıyor..."
	mkdir $HOME/filesystem
	7z x filesystem.RSU $HOME/filesystem
	sleep 2
	echo " "
	echo "[*] Dosya Sistemi Kullanılmak Üzere Ayarlanıyor..."
	chmod +x $HOME/filesystem
	mv $HOME/filesystem $HOME/../usr/share/rs_filesystem
	mv $HOME/../usr/share/rs_filesystem/user/bin/help.NA $HOME/../usr/share/rs_filesystem/user/bin/help
	mv $HOME/../usr/share/rs_filesystem/user/bin/linux.NA $HOME/../usr/share/rs_filesystem/user/bin/linux
	cat > $HOME/../usr/bin/rosa <<- _EOF_
		#!/data/data/com.termux/files/usr/bin/bash
		clear
		echo "#: "  
                read RS_COMMAND

                ./$HOME/../usr/share/rs_filesystem/user/bin/$RS_COMMAND

                not_clean() {
                	echo " "
                	echo "#: "  
                read RS_COMMAND

                ./$HOME/../usr/share/rs_filesystem/user/bin/$RS_COMMAND
                }

                ## Main
                if [[ "$1" == "--no-clear" ]]; then
                not_clean
                fi

        
	_EOF_
	if [[ -f "$HOME/../usr/bin/rosa" ]]; then
		echo -e ${RED}"[*] ${ORANGE} Kurulum Bitirildi! Başlatmak için ${GREEN}rosa ${ORANGE} yazın."
	fi	
}


## Banner
banner() {
	clear
    cat <<- EOF
        ${MAGENTA}┌─────────────────────────────────────────────────────────┐
        ${MAGENTA}│${CYAN}            ██████╗░░█████╗░░██████╗░█████╗░             ${MAGENTA}│
        ${MAGENTA}│${CYAN}            ██╔══██╗██╔══██╗██╔════╝██╔══██╗             ${MAGENTA}│
        ${MAGENTA}│${CYAN}            ██████╔╝██║░░██║╚█████╗░███████║             ${MAGENTA}│
        ${MAGENTA}│${CYAN}            ██╔══██╗██║░░██║░╚═══██╗██╔══██║             ${MAGENTA}│
        ${MAGENTA}│${CYAN}            ██║░░██║╚█████╔╝██████╔╝██║░░██║             ${MAGENTA}│
        ${MAGENTA}│${CYAN}            ╚═╝░░╚═╝░╚════╝░╚═════╝░╚═╝░░╚═╝             ${MAGENTA}│
        ${MAGENTA}└─────────────────────────────────────────────────────────┘
	EOF
}

## Show usages
usage() {
	banner
	echo -e ${ORANGE}"\nRosaOS"
	echo -e ${ORANGE}"Kullanım : $(basename $0) --kur | --kaldır | --onar \n"
}

	



## Main
if [[ "$1" == "--kur" ]]; then
	install_rs
elif [[ "$1" == "--kaldır" ]]; then
	uninstall_rs
elif [[ "$1" == "--onar" ]]; then
        repair_rs
else
	{ usage; reset_color; exit 0; }
fi
