#!/bin/bash


launcher_kurulum() {
	file="$HOME/../usr/bin/rosa"
	if [[ -f "$file" ]]; then
		rm -rf "$file"
	fi
	echo -e ${RED}"\n[*] ROSA Başlatma Komutları Hazırlanıyor... \n"
	{ reset_color; touch $file; chmod +x $file; }
	cat > $file <<- _EOF_
		#!/data/data/com.termux/files/usr/bin/bash
		# Export Display
		export DISPLAY=":1"
		# Start VNC Server
		if [[ \$(pidof Xvnc) ]]; then
		    echo -e "\\n[!] Sunucu Zaten Çalışıyor.."
		    { vncserver -list; echo; }
		    read -p "Kill VNC Server? (Y/N) : "
		    if [[ "\$REPLY" == "Y" || "\$REPLY" == "y" ]]; then
		        { killall Xvnc; echo; }
		    else
		        echo
		    fi
		else
		    echo -e "\\n[*] VNC Sunucusu Başlatılıyor.."
		    vncserver
		fi
	_EOF_
	if [[ -f "$file" ]]; then
		echo -e ${GREEN}"[*] ${ORANGE}$file ${GREEN}Script'i Hazırlandı!"
	fi
}


vnc_kurulum() {
	# backup old dir
	if [[ -d "$HOME/.vnc" ]]; then
		mv $HOME/.vnc{,.old}
	fi
	echo -e ${RED}"\n[*] VNC Ayarlanıyor.."
	{ reset_color; vncserver -localhost; }
	sed -i -e 's/# geometry=.*/geometry=1366x768/g' $HOME/.vnc/config
	cat > $HOME/.vnc/xstartup <<- _EOF_
		#!/data/data/com.termux/files/usr/bin/bash
		## This file is executed during VNC server
		## startup.
		# Launch Openbox Window Manager.
		xfce4-session &
	_EOF_
	if [[ $(pidof Xvnc) ]]; then
		    echo -e ${ORANGE}"[*] VNC Zaten Çalışıyor"
		    { reset_color; vncserver -list; }
	fi
}
 
echo "ROSA Kapatıldı! Güncelleme İşlemi Başlatılıyor..."
sleep 3
clear
echo "ROSA FIRMWARE UPDATER"
echo " "
echo "[*] Firmware Detecting..."
sleep 4
echo "[*] Firmware Detected (Magenta-1.0)"
sleep 3
echo "[*] Firmware Updating (Magenta-XFCE-1.0)"
sleep 6
echo "[*] Detecting Updated Firmware..."
sleep 3
echo "[*] Detected 'Magenta Firmware' "
sleep 3
echo "[*] installation in progress"
sleep 4
clear
 echo "FluxBox Kaldırılıyor..."
 sleep 2
 apt remove fluxbox
 clear
 echo "XFCE4 Kuruluyor..."
 sleep 2
 pkg install xfce4
 clear
 echo "ROSA 'XFCE4' İçin Kendini Yapılandırıyor..."
 sleep 2
 clear
 vncserver -kill :1
 vncserver -kill :2
 vncserver -kill :3
 vncserver -kill :4
 vncserver -kill :5
 vncserver -kill :6
 vncserver -kill :7 
 clear
 launcher_kurulum
 rm -rf $HOME/.vnc/config
 vnc_kurulum
 mv $HOME/../usr/bin/rosa/rosa $HOME/rosa.RSX
 rm -rf $HOME/../usr/bin/rosa
 mv $HOME/rosa.RSX $HOME/../usr/bin/rosa
 chmod +x $HOME/../usr/bin/rosa
 echo "ROSA İçin 'XFCE4' Kuruldu. Başlatmak için "rosa" yazın."
