#!/data/data/com.termux/files/usr/bin/bash
		# Export Display
		export DISPLAY=":1"
		# Start VNC Server
		if [[ \$(pidof Xvnc) ]]; then
		    echo -e "\\n[!] Sunucu Zaten Çalışıyor.."
		    { vncserver -list; echo; }
		    read -p "Kill VNC Server? (Y/N) : "
		    if [[ "\$REPLY" == "Y" || "\$REPLY" == "y" ]]; then
		        { killall Xvnc; echo; }
		    else
		        echo
		    fi
		else
		    echo -e "\\n[*] VNC Sunucusu Başlatılıyor.."
		    vncserver
		fi
